name: Build and Test Maven Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Baixar código repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Compilar projeto com Maven
      - name: Build with Maven
        run: mvn clean install

      # Roda testes
      - name: Run Tests
        run: mvn test
